name: Build and Test (only)

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]

    steps:
    - name: Get source
      uses: actions/checkout@v1

    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100

    - name: Build
      run: dotnet build -c Release -v minimal -p:WarningLevel=3

    - name: Test
      run: dotnet test -c Release --no-build --filter '(TestCategory!=LongRunning)&(TestCategory!=Stress)&(TestCategory!=FailureCase)'
      shell: bash # defaults disagree on how to quote the filter string

    - name: Pack
      run: dotnet pack -c Release --no-build -o artifacts -p:NoWarn=NU5105

    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: NuGet Package Files (${{ matrix.os }})
        path: artifacts

